- path: /releases/name=simple-go-web-app/url
  type: replace
  value: "https://s3.amazonaws.com/simple-go-web-app-boshrelease/compiled-releases/simple-go-web-app-1.0.0-ubuntu-trusty-3541.10-20180404-021056-229617666-20180404021102.tgz"
- path: /releases/name=simple-go-web-app/version
  type: replace
  value: "1.0.0"
- path: /releases/name=simple-go-web-app/sha1
  type: replace
  value: "06399514661308f2feba36c7f019aff54a5674eb"

- path: /releases/name=simple-go-web-app/stemcell?
  type: replace
  value:
    os: "ubuntu-trusty"
    version: "3541.10"
