---
name: simple-go-web-app

addons:
- name: bpm
  jobs:
  - name: bpm
    release: bpm

instance_groups:
- name: simple-go-web-app
  azs: [z1, z2, z3]
  instances: 1
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: simple-go-web-app
    release: simple-go-web-app
    properties: {}

variables: []

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 1
  serial: false

releases:
- name: bpm
  url: git+https://github.com/cloudfoundry-incubator/bpm-release
  version: 0.5.0
- name: simple-go-web-app
  sha1: 10db8b2b774f0eb2f76756d863f4f07df3cb3afe
  url: https://github.com/cloudfoundry-community/simple-go-web-app-boshrelease/releases/download/v1.0.0/simple-go-web-app-1.0.0.tgz
  version: 1.0.0
